const variants_adventures = [
  {
    description: "",
    dok_filter: "",
    format: "adventures",
    fn: () => {},
    tco: false,
    variant: "keyraken",
  },
  {
    description: "",
    dok_filter: "",
    format: "adventures",
    fn: () => {},
    tco: false,
    variant: "abyssal conspiracy",
  },
  {
    description: "",
    dok_filter: "",
    format: "adventures",
    fn: () => {},
    tco: false,
    variant: "fall of the house gormangeist",
  },
  {
    description: "",
    dok_filter: "",
    format: "adventures",
    fn: () => {},
    tco: false,
    variant: "great hunt",
  },
  {
    description: "",
    dok_filter: "",
    format: "adventures",
    fn: () => {},
    tco: false,
    variant: "archenvy",
  },
  {
    description: "",
    dok_filter: "",
    format: "adventures",
    fn: () => {},
    tco: false,
    variant: "total distruction",
  },
  {
    description: "",
    dok_filter: "",
    format: "adventures",
    fn: () => {},
    tco: false,
    variant: "flight of the royal fortune",
  },
];
