const variants_multiplayer = [
  {
    description: "",
    dok_filter: "",
    format: "multiplayer",
    fn: () => {},
    tco: false,
    variant: "keymander",
  },
  {
    description: "",
    dok_filter: "",
    format: "multiplayer",
    fn: () => {},
    tco: false,
    variant: "crucible clash",
  },
  {
    description: "",
    dok_filter: "",
    format: "multiplayer",
    fn: () => {},
    tco: false,
    variant: "archon doubles",
  },
  {
    description: "",
    dok_filter: "",
    format: "team",
    fn: () => {},
    tco: true,
    variant: "triad_team_archon",
  },
  {
    description: "open 9 decks, pick one for each format",
    dok_filter: "",
    format: "team",
    fn: () => {},
    tco: true,
    variant: "archon/reversal/adaptive short",
  },
  {
    description: "",
    dok_filter: "",
    format: "team",
    fn: () => {},
    tco: true,
    variant: "archon/reversal/adaptive short alliance",
  },
];
