// https://archonarcana.com/Unofficial_Variants,_Tournament_Structures,_and_House_Rules
// Variants are different ways to play format

// tco: can the variant be played on TCO easily?
const variants = [
  {
    description: "Each player starts the match with X (12) chains.",
    dok_filter: "",
    fn: () => {},
    format: "archon",
    tco: true,
    variant: "chained_down",
  },
  {
    description:
      "Each player brings a WoE deck but can use any token creature.",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: false,
    variant: "token_creature_any",
  },
  {
    description:
      "Each player brings a deck and for each match bids chains on which deck to play.",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "adaptive_short_archon",
  },
  {
    description: "The game continues until a player forges 4 keys.",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "key4ge",
  },
  {
    description: "Each player brings a deck and for each match plays with the deck their opponent brought.",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "reversal",
  },
  {
    description: "Each player finds a deck on DoK with a minimum SAS of X (90).",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "net_deck",
  },
  {
    description: "The deck with higher SAS starts with chains based the difference in SAS.",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "sas_difference",
  },
  {
    description: "Each round alternates between archon and reversal, with the first round being randomly selected.",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "tesla",
  },
  {
    description: "At the end of each match, swap decks with your opponent.",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "telephone",
  },
 
  {
    description: "",
    dok_filter: "",
    format: "multiplayer",
    fn: () => {},
    tco: false,
    variant: "break-key",
  },
  {
    description: "",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: false,
    variant: "civil war",
  },
  {
    description: "",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: false,
    variant: "dark aember",
  },
  {
    description: "",
    dok_filter:
      "https://www.reddit.com/r/KeyforgeGame/comments/p1ofi5/shredder_at_pink_bunny_games_9aug21/",
    fn: () => {},
    format: "archon",
    tco: false,
    variant: "shredder",
  },
  {
    description: "",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "triad_short_archon",
  },
  {
    description: "",
    dok_filter: "",
    format: "sealed",
    fn: () => {},
    tco: true,
    variant: "triad_short_sealed",
  },
  {
    description: "ban a house, present 2 decks",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "oubliette",
  },
  {
    description: "draft houses until you have 3 houses, then find a deck with those houses",
    dok_filter: "",
    fn: () => {},
    format: "archon",
    tco: false,
    variant: "snaglet's mirror",
  },
  {
    description: "",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    in_person: "",
    variant: "gemini",
  },
  {
    description:
      "3 decks, play archon, reversal, adaptive with opponent choosing which deck",
    dok_filter: "",
    fn: () => {},
    format: "archon",
    tco: false,
    variant: "moirai",
  },
  {
    description: "",
    dok_filter: "",
    format: "draft",
    fn: () => {},
    in_person: "",
    variant: "auction",
  },
  {
    description: "",
    dok_filter: "",
    format: "draft",
    fn: () => {},
    in_person: "",
    variant: "house drafting",
  },
  {
    description: "",
    dok_filter: "",
    format: "draft",
    fn: () => {},
    in_person: "",
    variant: "veto",
  },
  {
    description:
      "bring 2 decks, houses are banned each round randomly based on representation",
    dok_filter: "",
    fn: () => {},
    format: "archon",
    tco: true,
    variant: "ouroboros",
  },
  {
    description: "",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: false,
    variant: "evil twin",
  },
  {
    description: "",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "survival",
  },
  {
    description: "",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "loot the bodies",
  },
  {
    description: "Best of 5 games, first to forge a key wins each game.",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "100_meter_dash",
  },
  {
    description: "deck must include 4 copies of a card",
    dok_filter: "",
    format: "archon",
    fn: () => {},
    tco: true,
    variant: "quadruplet",
  },
];
